name: Build and Push Docker Images

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    services:
      docker:
        image: docker:19.03.12
        options: --privileged

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Install dependencies
        run: echo "nothing needs to be installed"

      - name: Before script (logging)
        run: echo "no tests"

      - name: Print Docker version
        run: docker --version

      - name: Build Docker Images
        run: |
          ls
          docker build -f ./udagram-frontend/DockerFile -t udagram-frontend .
          docker build -f ./udagram-api-feed/DockerFile -t udagram-api-feed .
          docker build -f ./udagram-api-user/DockerFile -t udagram-api-user .
          docker build -f ./udagram-reverseproxy/DockerFile -t udagram-reverseproxy .

      - name: Tag Docker Images
        run: |
          docker tag udagram-api-feed ${{ secrets.DOCKER_REPO }}/udagram-api-feed:v1
          docker tag udagram-api-user ${{ secrets.DOCKER_REPO }}/udagram-api-user:v1
          docker tag udagram-api-frontend ${{ secrets.DOCKER_REPO }}/udagram-api-frontend:v1
          docker tag udagram-reverseproxy ${{ secrets.DOCKER_REPO }}/udagram-reverseproxy:v1

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Push Docker Images
        run: |
          docker push ${{ secrets.DOCKER_USERNAME }}/udagram-api-feed:v1
          docker push ${{ secrets.DOCKER_USERNAME }}/udagram-api-user:v1
          docker push ${{ secrets.DOCKER_USERNAME }}/udagram-api-frontend:v1
          docker push ${{ secrets.DOCKER_USERNAME }}/udagram-reverseproxy:v1
